[build-system]
requires = ["setuptools<82"]
build-backend = "setuptools.build_meta"

[project]
name = "prospero"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "biotite>=1.0.0",
    "evodiff>=1.1.0",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "pandas>=2.3.3",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.0",
    "tape-proteins",
    "torch==2.5.1",
    "tqdm>=4.67.3",
    "transformers>=4.47,<4.48.2",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
exclude = ["src/prospero/experiments_config.py"]

[dependency-groups]
dev = [
    "pyright>=1.1.411",
    "pytest>=9.1.1",
    "ruff>=0.15.22",
]
